# Generated by Django 5.2.5 on 2026-04-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store',
            new_name='name',
        ),
    ]
